apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: postgresql-credentials
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: postgresql-credentials
      namespace: ${NAMESPACE}
    type: Opaque
    stringData:
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      DB_DSN: "host=postgresql port=5432 user=${POSTGRESQL_USER} password=${POSTGRESQL_PASSWORD} dbname=boss sslmode=disable"
parameters:
  - name: NAMESPACE
    required: true
    value: jsell-agent-boss
  - name: POSTGRESQL_USER
    required: true
    value: boss
  - name: POSTGRESQL_PASSWORD
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{16}"
